Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view war.views.r_index didn't return an HttpResponse object. It returned None instead.
Not Found: /favicon.ico
Not Found: /country/2
Not Found: /war/country/2
Not Found: /admin
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 212, in inner
    if not self.has_permission(request):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 212, in inner
    if not self.has_permission(request):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 212, in inner
    if not self.has_permission(request):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 212, in inner
    if not self.has_permission(request):
  File "C:\Users\Administrator\.virtualenvs\ac-uK-qyzEl\lib\site-packages\django\contrib\admin\sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
AttributeError: 'WSGIRequest' object has no attribute 'user'
